import { useNavigate } from "react-router-dom";
import {
  FileText,
  Image as ImageIcon,
  Video,
  Mic,
  BrainCircuit,
  ShieldAlert,
} from "lucide-react";
import { Button } from "@/components/ui/button";

export default function DetectionTools() {
  const navigate = useNavigate();

  const tools = [
    {
      title: "Fake News Detection",
      description: "Identify misinformation and verify news authenticity",
      icon: <FileText className="h-6 w-6 text-white" />,
      color: "bg-orange-500",
    },
    {
      title: "Image Deepfake Scanner",
      description: "Detect AI-generated and manipulated images",
      icon: <ImageIcon className="h-6 w-6 text-white" />,
      color: "bg-blue-600",
    },
    {
      title: "Video Authenticity Check",
      description: "Analyze videos for deepfake manipulation",
      icon: <Video className="h-6 w-6 text-white" />,
      color: "bg-green-500",
    },
    {
      title: "Voice Clone Detection",
      description: "Identify AI-generated and synthetic audio",
      icon: <Mic className="h-6 w-6 text-white" />,
      color: "bg-yellow-500",
    },
    {
      title: "AI Text Detector",
      description: "Spot content generated by language models",
      icon: <BrainCircuit className="h-6 w-6 text-white" />,
      color: "bg-purple-600",
    },
    {
      title: "Malware Scanner",
      description: "Scan files and URLs for security threats",
      icon: <ShieldAlert className="h-6 w-6 text-white" />,
      color: "bg-red-500",
    },
  ];

  return (
    <section className="bg-muted/50 py-20">
      <div className="container mx-auto px-4 md:px-6">
        {/* Header */}
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Choose Your Detection Tool
          </h2>
          <p className="mt-3 text-lg text-muted-foreground">
            Advanced AI-powered tools to verify content authenticity and detect
            digital threats
          </p>
        </div>

        {/* Tools Grid */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {tools.map((tool, index) => (
            <div
              key={index}
              className="flex flex-col items-center rounded-xl bg-card p-6 text-center shadow-sm ring-1 ring-border transition-all hover:shadow-md hover:ring-primary/20"
            >
              {/* Circular Icon */}
              <div
                className={`mb-5 flex h-14 w-14 items-center justify-center rounded-full shadow-sm ${tool.color}`}
              >
                {tool.icon}
              </div>

              {/* Text Content */}
              <h3 className="mb-2 text-lg font-bold text-foreground">
                {tool.title}
              </h3>
              <p className="mb-6 text-sm text-muted-foreground leading-relaxed">
                {tool.description}
              </p>

              {/* Button - Pushed to bottom */}
              <div className="mt-auto w-full">
                <Button
                  variant="outline"
                  className="w-full bg-background hover:bg-muted hover:text-foreground hover:scale-105 hover:border-primary transition-all duration-300"
                  onClick={() => navigate("/auth")}
                >
                  Try Now
                </Button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
